### ISSUE TITLE
No image...

### ISSUE THREAD

**Issue by sapioit** [synthtech/minimal-kissanime#1]
When in the anime's page, the thumbnail from the right side is missing...
Let's take, for example, http://kissanime.com/Anime/Noragami-Aragoto

**Comment by synthtech** [comment]
It's intentional. I didn't like how the majority of the content in the sidebar was just suggested links so I just hid the whole thing.

**Comment by sapioit** [comment]
I would have chosen to only show that image, in the div with the text, with the image aligned to the right.

**Comment by synthtech** [comment]
I just feel it's a bad design choice on their part.

Anyways, I could create a userstyle option that would show the sidebar if a user chooses to opt-in to it.

**Comment by sapioit** [comment]
You can use JS to take the image's URL from the panel you deleted, and add it in the div with the text, with the style="float:right;"

**Comment by synthtech** [comment]
Sorry for the delay, the sidebar option should now be available on Userstyles.

Should look like this: ![](https://puu.sh/leHDx/35ade02b69.png)

My js knowledge is pretty weak, so I probably won't be making a userscript for that anytime soon.

**Comment by sapioit** [comment]
Thanks!
