### ISSUE TITLE
Ad Blocker Broken? Video Blocked

### ISSUE THREAD

**Issue by Sarabveer** [synthtech/minimal-kissanime#2]
KissAnime now blocks the video being played if Minimal KissAnime is applied. (I know since my AdBlocker is turned off).

![](http://puu.sh/lfXL1/2e15c55539.jpg)

**Comment by synthtech** [comment]
Looks like I forgot to test the HTML5 player. I just pushed a new update that should fix it.

**Comment by Sarabveer** [comment]
Yea I just read they updated their Anti-AdBlock Detection System they have.

Nice theme by the way

+1

**Comment by synthtech** [comment]
Ah, thanks
